### ISSUE TITLE
com.sun.tools.javac.code.Symbol$CompletionFailure

### ISSUE THREAD

**Issue by willf80** [mahimrocky/TagView#1]
com.sun.tools.javac.code.Symbol$CompletionFailure: class file for com.google.android.flexbox.FlexboxLayout not found.

When I try to get TagView
`TagView tagView = findViewById(R.id.tag_view_test);
`

**Comment by W3-Tariqul** [comment]
I cannot find the issue . But if you get continuous this issue please add this dependency in your app gradle implementation 'com.google.android:flexbox:1.0.0'
And i think you clone the project. If you you use this library by gradle implementation like: implementation 'com.github.mahimrocky:TagView:1.0.1' I think you never get this error.

So i closed the issue. Sorry for late reply

**Comment by mahimrocky** [comment]
I cannot find the issue . But if you get continuous this issue please add this dependency in your app gradle implementation 'com.google.android:flexbox:1.0.0'
And i think you clone the project. If you you use this library by gradle implementation like: implementation 'com.github.mahimrocky:TagView:1.0.1' I think you never get this error.

So i closed the issue. Sorry for late reply
